---
 - hosts: all
   become: yes
   remote_user: bootcamp   

   tasks:   
   - name: Get public IP
     community.general.ipify_facts:
   
   - name: Delete previous deploy directory
     file: 
       path: '{{ app_directory }}'
       state: absent
                      
