---
 - hosts: all
   become: yes
   remote_user: bootcamp   

   tasks:   
   - name: Get public IP
     community.general.ipify_facts:
   
   - name: Delete previous deploy directory
     file: 
       path: '{{ app_directory }}'
       state: absent
       
   - name: Create Directory
     file: 
       path: /home/bootcamp/bootcamp-app
       state: directory
       mode: '0755'


   - name: Synchronization of src on the control machine to dest on the remote hosts
     ansible.posix.synchronize:
       src:  /home/agent/agent/_work/r2/a/bootcamp-app
       dest: /home/bootcamp/
       
     
   
